import Head from 'next/head'
import Header from '@/componentes/Header'
import React from 'react';
import DynaPredict from '@/componentes/DynaPredict';
import Senores from '@/componentes/Sensores';
import Contact from '@/componentes/Contato';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <DynaPredict/>
        <Senores />
        <Contact />
      </main>
    </>
  )
}
